### ISSUE TITLE
setting dip25 in dub.json is infectious

### ISSUE THREAD

**Issue by John-Colvin** [msgpack/msgpack-d#110]
It means that all code involved in the build must be dip25 compliant.

**Comment by Basile-z** [comment]
It was added a bit prematurely because of a DMD PR that proposed to make -dip25 the default. 
Then people started to add the switch to the projects tested in the dlang project tester, in order to make the CI green, but finally the PR was closed.

So you can remove it.

**Comment by Basile-z** [comment]
No need to make a PR finally, I've added a commit in the PR I had opened on the same day, since it's related.
