### ISSUE TITLE
Build requires "WS2_32" library on all platforms

### ISSUE THREAD

**Issue by Hackerpilot** [msgpack/msgpack-d#118]
This commit https://github.com/msgpack/msgpack-d/commit/a23181e14c0c4bc6a416ad0c712678c7ee8b3b21 introduced a `pragma(lib, "WS2_32");` statement outside of any `version` statement, making the code fail to build on non-Windows platforms. This needs to be placed into some sort of conditional compilation block.

**Comment by repeatedly** [comment]
Ah, sorry. I forgot to merge this issue: https://github.com/msgpack/msgpack-d/pull/117
