### ISSUE TITLE
Version tag for 26ef07e

### ISSUE THREAD

**Issue by nordlow** [msgpack/msgpack-d#130]
Please create a version tag for 26ef07e16023483ad93e3f86374b19d0e541c924.

**Comment by lempiji** [comment]
I'm sorry for the delay. I've made a release. How does it look?

https://github.com/msgpack/msgpack-d/releases/tag/v1.0.5

**Comment by nordlow** [comment]
Excellent. Thanks.

**Comment by nordlow** [comment]
Can somebody be so kind to bump the version tag at https://code.dlang.org/packages/msgpack-d aswell? code.dlang.org doesn't currently auto-sync.
