### ISSUE TITLE
Serialization of std.container.Array and alikes

### ISSUE THREAD

**Issue by nordlow** [msgpack/msgpack-d#44]
It would be nice to have support for `std.container`, in my case `Array`.

This is what I have until this, potentially, gets supported by msgpack-d.

```D
import std.stdio;
import std.conv: to;
import std.container: Array;
import msgpack;

static void stringArrayPackHandler(E)(ref Packer p,
                                      ref Array!E x)
{
    foreach (e; x)
        p.pack(e);
}

unittest
{
    registerPackHandler!(Array!string, stringArrayPackHandler);
    Array!string x = ["x", "y"];
    writeln(x.pack);
    writeln(["x", "y"].pack);
}
```

It outputs

```
[161, 120, 161, 121]
[146, 161, 120, 161, 121]
```

If this will not be implemented in msgpack, how do I, at least, write the byte `146` rawly to `p` to make the serialization match the type `string[]`?

Removing the call to `registerPackHandler`

makes the test program above fail as

```
core.exception.AssertError@std/container/array.d(44): Assertion failure
```

Is this the `std.container.Array`'s fault?

**Comment by repeatedly** [comment]
Close it.
After std.container API is finished, I will add more general support instead of isArray.
