### ISSUE TITLE
Segmentation fault reading Spec 5 data

### ISSUE THREAD

**Issue by jwhear** [msgpack/msgpack-d#45]
```
import std.stdio, std.file;
import msgpack;
void main(string[] args)
{
	auto input = cast(ubyte[])read("test.msg");
	auto data = unpack(input);
	foreach (v; data)
		writeln(v.type);
}
```

Github only allows attaching of images, so I've base64 encoded the data here: http://pastebin.com/vSj7GH6a

```
$ base64 -d <test.b64 >test.msg
$ md5sum test.msg
4a6a770f293f1e1126d108ce85a79fd6  test.msg
```

For reference the results of using a simple python script to translate test.msg to JSON is here: http://pastebin.com/zdmH924s
.

**Comment by repeatedly** [comment]
Thanks!
I will check this problem later after waked up.

**Comment by repeatedly** [comment]
Ah, this is not new spec problem.
`Unpacked` InputRange assumes the result is array.
But your json is map so it causes the segfault: https://github.com/msgpack/msgpack-d/blob/878fcb1852160d1c3d206df933f6becba18aa222/src/msgpack.d#L3863

Writing following code works:

```rb
void main(string[] args)
{
    // ...
    auto data = unpack(input);
    foreach (k, v; data.value.via.map)
        writeln(cast(string)k.via.raw);  # print keys
}
```

Hmm... InputRange seems to hard to support Map like key value pair.
Should we add `opApply`?

**Comment by jwhear** [comment]
Ah, I see.  Perhaps in debug mode those front operations could enforce that the type of value is what is expected so that a sensible error message is thrown?

**Comment by repeatedly** [comment]
Good idea. I will implement it later!
