### ISSUE TITLE
convert from/to json

### ISSUE THREAD

**Issue by yannick** [msgpack/msgpack-d#48]
is there a way to convert from/to json ?

**Comment by repeatedly** [comment]
What does json mean? std.json?

**Comment by yannick** [comment]
e.g. via std.json or directly into/from a json string.
basically what is done here https://github.com/tv42/msgpack-json
is that already possible?

**Comment by repeatedly** [comment]
Maybe possible by writing msgpack.Value to JSONValue or JSONValue to msgpack.Value converter for std.json.
With yajl-d, struct as a temporary object is an another approach.
