### ISSUE TITLE
Don't know how to construct class type 'S' with argument types '()'

### ISSUE THREAD

**Issue by timotheecour** [msgpack/msgpack-d#54]
Seems like msgpack-d requires empty constructor for classes.
Can we relax this?
Classes could be allocated without calling 'new' constructor to enable this.

**Comment by repeatedly** [comment]
You mean Unpacker?
Unpacker's class deserialization requires arguments of constructor, not empty constructor.

https://github.com/msgpack/msgpack-d/blob/b068112a0b099a9d0eaab980cd9c68fa782d3dda/src/msgpack.d#L2649

Could you show me your code example?

**Comment by timotheecour** [comment]
Yes, Unpacker.
Actually I'm not sure anymore.
Here's an example adapted from http://wiki.dlang.org/Memory_Management but without calling emplace (which has same restrictions as new, as does Object.factory apparently).

class A{
  int x=2;
  this(int x){
    this.x=x;
  }
}

void test(){
  A a=allocClass!A;
  // works but not sure how safe this is
}

T allocClass(T, Args...) (Args args) {
  import core.stdc.stdlib : malloc;
  import core.memory : GC;
  auto size = __traits(classInstanceSize, T);
  auto memory = malloc(size)[0..size];
  assert(memory);

  // instead of 0-fill, would fill up the buffer from deserialization
  (cast(byte[])memory)[]=0;

  GC.addRange(memory.ptr, size);
  return cast(T)cast(void*)memory;
}

**Comment by timotheecour** [comment]
Started a thread here: http://forum.dlang.org/thread/mailman.105.1432199217.7663.digitalmars-d-learn@puremagic.com [deserialization: creating a class instance without calling constructor]

Some proposed:

CT construct(CT, A...)(A a)
if (is(CT == class))
{
    auto memory = malloc(typeid(CT).init.length);
    memory[0 .. typeid(CT).init.length] = typeid(CT).init[];
    return cast(CT) memory;
}

**Comment by repeatedly** [comment]
I know we can use manual construction without new for classes.

> Could you show me your code example?

This means I want to know what the code causes `Don't know how to construct class type 'S' with argument types '()'`.
But I noticed you call unpack like below:

```d
class A
{
    this(int a) { }
}

A a;
unpacker.unpack(a, 10);  // ok
unpacker.unpack(a);  // error
```

Latter case is error prone but it seems acceptable. I will support it.

**Comment by timotheecour** [comment]
Ah I forgot about ` _d_newclass`, it's simpler indeed! Thanks, the patch works
