### ISSUE TITLE
register derived class without a custom handler

### ISSUE THREAD

**Issue by timotheecour** [msgpack/msgpack-d#55]
Registering a derived class should not require a custom handler, it should allow the following:

//custom code
registerPackHandler!(Subclass, cPackHandler);

//MISSING: default 'pack' code applied to derived Subclass when given a base class reference
registerPackHandler!(Subclass);

(likewise with unpack)

see how it's done with orange:

Serializer.register!(Sub);
https://github.com/jacob-carlborg/orange/blob/d5b2e0127c67f50bd885ee43a7dd61dd418b1661/tests/BaseClass.d#L58

**Comment by repeatedly** [comment]
Hm. I don't know orange way but using downcast in default handler may resolve this issue.
I will try it.

**Comment by timotheecour** [comment]
As it is currently, I see no way to call the default handler for derived class using the provided APIs, since calling 'pack' from a custom handler cPackHandler will give infinite loop (as it'll in turn call the custom handler); 
so the only way is for msgpack-d API has to provide it (eg as suggested above). Thanks for working on it! Hopefully it's a simple fix :-)

**Comment by repeatedly** [comment]
I wrote a patch for this issue.
Could you test https://github.com/msgpack/msgpack-d/pull/57 code on your case?

**Comment by timotheecour** [comment]
thanks! it works :-)

**Comment by timotheecour** [comment]
Actually it doesn't work in this simple case:

msgpack.MessagePackException@msgpack.d(282): Attempt to unpack with non-compatible type
maybe something involving a map:
ClassInfo[size_t]
and then each registered ClassInfo is accessible via a unique integer identifier that is serialized as a header to each class instance?

```d
import msgpack;
class A{
  B b;
  this(int a){}
}

class B{
  double y;
}

class B2:B{
    double z;
    this(double z){
        this.y=z;
        this.z=z;
    }
}

void main(){
  registerClass!B2;
  auto a=new A(0);
  a.b=new B2(4);

  auto data = pack(a);
  auto a2 = unpack!A(data);
}
```

**Comment by repeatedly** [comment]
> Actually it doesn't work in this simple case:

This is an another problem.
MessagePack is an efficient binary serialization for exchanging between multiple languages
and its format doesn't define complex structure like inheritance or similar.

So I think this problem is an outside of msgpack-d.
For example, java users use jackson-databind for such purpose.
If we want to keep object graph completely with data container format,
we should follow jackson or similar approach.

**Comment by repeatedly** [comment]
Or another approach is adding `@packAsObject` attribute for `B b` like fields.
If find `@packAsObject`, msgpack-d serializes object into map with typeinfo, not array.

**Comment by timotheecour** [comment]
>> Or another approach is adding @packAsObject attribute for B b

I don't think the user types should be touched with @packAsObject in this simple case just to support this. This is a very common case and people will be reluctant to use this if they have to change their classes.

>> So I think this problem is an outside of msgpack-d.

That's too bad. There's a real need for this IMO; at least as an option (it's ok to break compatibility with other languages for this purpose as an option). If msgpack-d can't support this use case I'll have to consider forking this project. 

Also, it seems to me the test case in the above example ("Actually it doesn't work in this simple case:") would also apply to the standard registerPackHandler!(Subclass, cPackHandler) handler as well (haven't checked though).

>> For example, java users use jackson-databind for such purpose.

I can't find any D binding for this (is there?). Also, I'm not sure what are the tradeoffs (performance, size, type safety, flexibility) wrt msgpack?
