### ISSUE TITLE
unpack withFields into Type

### ISSUE THREAD

**Issue by yannick** [msgpack/msgpack-d#63]
is it possible to unpack a message that contains the fieldnames into a type?

the following fails:
( Attempt to unpack with non-compatible type )

```
import std.stdio;
import msgpack;

shared struct Test 
{
  @property string a;
  @property  string b;
  
}

void main()
{
	
  Test a = Test();
  writeln(a);
  auto p = a.pack!true();
  writeln(p);
  auto b = p.unpack!(Test, true)();
  writeln(b);
  
}
```

**Comment by repeatedly** [comment]
msgpack packs objects as an array in general, e.g. all msgpack libraries do.
Packing objects as a map is for flunetd like system.
What is the use-case?

**Comment by yannick** [comment]
use case was legacy setup and a easy transform to json. 
i now changed it though. would still be cool to have though
