### ISSUE TITLE
string or null pack / unpack crashes

### ISSUE THREAD

**Issue by anton-dutov** [msgpack/msgpack-d#77]
Code

    string src;
    writefln("Packed '%s'", src.pack);
    writefln("Unpacked '%s'", src.pack.unpack);

Output

    Packed '[192]'
    object.Exception@../../../.dub/packages/msgpack-d-1.0.0-beta.2/src/msgpack.d(4599): front is called with non array object. type = nil

Same issue for code

    writefln("Packed '%s'", null.pack);
    writefln("Unpacked '%s'", null.pack.unpack);

Packing is 192 == 0xC0 == Nil
AFAIK should be 160 == 0xA0 == Fixed string

Ok now trying unpack empty string

    writefln("Unpacked '%s'", [0xA0].unpack);

Fails

    msgpack.UnpackException@../../../.dub/packages/msgpack-d-1.0.0-beta.2/src/msgpack.d(305): Deserialization failure

**Comment by repeatedly** [comment]
```
Packed '[192]'
object.Exception@../../../.dub/packages/msgpack-d-1.0.0-beta.2/src/msgpack.d(4599): front is called with non array object. type = nil
```

This is expected behaviour. `Unpacked` is a range object so you should check value type before calling Range API.

> writefln("Packed '%s'", null.pack);
> Packing is 192 == 0xC0 == Nil
> AFAIK should be 160 == 0xA0 == Fixed string

What does this sentence mean?
`null` is not string so msgpack can't serialize `null` as fixed string.

**Comment by anton-dutov** [comment]
> Packing is 192 == 0xC0 == Nil
> AFAIK should be 160 == 0xA0 == Fixed string
Sory, that description for first code sample
