### ISSUE TITLE
FYI: Deprecation Message Received During Build/Compilation

### ISSUE THREAD

**Issue by chuckmoore55** [msgpack/msgpack-d#79]
Hi,

Got this during build/compile on Windows:
Error	1	Deprecation: module std.c.windows.winsock is deprecated - Import core.sys.windows.winsock2 instead	C:\MyProgramFiles\msgpack-d-master\src\msgpack\common.d	14	

(manually) fixed the 'common.d' source line per the error message recommendation and it now builds/compiles without the message.

Just letting y'all know,
Chuck

**Comment by repeatedly** [comment]
Thanks for the notification.
I will fix it later!

**Comment by repeatedly** [comment]
Fixed
