### ISSUE TITLE
Build error on prominent place in http://msgpack.org/

### ISSUE THREAD

**Issue by andre2007** [msgpack/msgpack-d#96]
D/msgpack is on the top right of the languages while opening the page http://msgpack.org/.
That is fantastic! But the first thing you see while click on D/msgpack is: **build error**

**Comment by repeatedly** [comment]
What does "build error" mean?
There is no error on my browser.

https://gyazo.com/b7fc685b4f504d6b74d7a0340223369a.png

**Comment by andre2007** [comment]
There is the gray in gray picture from the readme markdown file.
If it means that there is no build error, the picture is quite misleading.

https://travis-ci.org/msgpack/msgpack-d

**Comment by John-Colvin** [comment]
https://github.com/msgpack/msgpack-d/pull/91

**Comment by andre2007** [comment]
Close as issue is solved.
Thank you.
